### ISSUE TITLE
Undefined Function Error: nil.admin_path/2

### ISSUE THREAD

**Issue by nickarora** [smpallen99/ex_admin#148]
After following the setup instructions, and launching phoenix.server, localhost:4000/admin fails to load.  The following error is displayed:

```
Server: localhost:4000 (http)
Request: GET /admin
** (exit) an exception was raised:
    ** (UndefinedFunctionError) undefined function nil.admin_path/2
        nil.admin_path(nil, :dashboard)
        (ex_admin) lib/ex_admin/navigation.ex:31: ExAdmin.Navigation.nav_link/3
        (ex_admin) lib/ex_admin/navigation.ex:24: anonymous fn/4 in ExAdmin.Navigation.nav_view/2
        (elixir) lib/enum.ex:1473: Enum."-reduce/3-lists^foldl/2-0-"/3
        (ex_admin) lib/ex_admin/navigation.ex:23: ExAdmin.Navigation.nav_view/2
        (ex_admin) web/templates/themes/admin_lte2/layout/header.html.eex:54: ExAdmin.AdminLte2.LayoutView."header.html"/1
        (ex_admin) web/templates/layout/admin_lte2.html.eex:41: ExAdmin.LayoutView."admin_lte2.html"/1
        (phoenix) lib/phoenix/view.ex:344: Phoenix.View.render_to_iodata/3
        (phoenix) lib/phoenix/controller.ex:633: Phoenix.Controller.do_render/4
        (ex_admin) web/controllers/admin_controller.ex:1: ExAdmin.AdminController.action/2
        (ex_admin) web/controllers/admin_controller.ex:1: ExAdmin.AdminController.phoenix_controller_pipeline/2
        (admin) lib/phoenix/router.ex:261: Admin.Router.dispatch/2
        (admin) web/router.ex:1: Admin.Router.do_call/2
        (admin) lib/admin/endpoint.ex:1: Admin.Endpoint.phoenix_pipeline/1
        (admin) lib/plug/debugger.ex:93: Admin.Endpoint."call (overridable 3)"/2
        (admin) lib/phoenix/endpoint/render_errors.ex:34: Admin.Endpoint.call/2
        (plug) lib/plug/adapters/cowboy/handler.ex:15: Plug.Adapters.Cowboy.Handler.upgrade/4
        (cowboy) src/cowboy_protocol.erl:442: :cowboy_protocol.execute/4
```

Running using:
Phoenix: 1.1.6
Phoenix_ecto: 3.0.0
Ecto: 2.0.0-rc6

For reference --
mix.exs
```
  def application do
    [mod: {Admin, []},
     applications: [:phoenix, :phoenix_html, :cowboy, :logger, :gettext,
                    :phoenix_ecto, :mariaex, :geocoder, :tzdata, :ex_admin]]
  end

...

  defp deps do
    [{:phoenix, "~> 1.1.6"},
     {:mariaex, "~> 0.7.7"},
     {:phoenix_ecto, "~> 3.0.0-rc"},
     {:phoenix_html, "~> 2.6"},
     {:phoenix_live_reload, "~> 1.0", only: :dev},
     {:gettext, "~> 0.9"},
     {:cowboy, "~> 1.0"},
     ...
     {:ex_admin, github: "smpallen99/ex_admin"}]
```
router.ex
```
defmodule Admin.Router do
  use Admin.Web, :router
  use ExAdmin.Router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/admin", ExAdmin do
    pipe_through :browser
    admin_routes
  end

  scope "/", Admin do
    ...
  end
end

```

config.exs
```
config :xain, :after_callback, {Phoenix.HTML, :raw}

config :ex_admin,
  repo: Admin.Repo,
  module: Admin,
  modules: [
    Admin.ExAdmin.Dashboard,
  ]
```

endpoint.ex
```
...
  plug Plug.Static,
    at: "/", from: :nested, gzip: false,
    only: ~w(css fonts images js themes favicon.ico robots.txt)
```

Below commands were run before starting the server, with no errors
```
mix do deps.get, deps.compile
mix admin.install
```

**Comment by nickarora** [comment]
Additional info, I've now added a reference to the SHA directly before [this commit](https://github.com/smpallen99/ex_admin/commit/f1c9a9bbcc1cf1ef149423efc33a7567b40720ef) and everything appears to be working correctly.  I believe a bug was introduced when the admin_path helper was created

**Comment by smpallen99** [comment]
@nickarora  Your right. I get the same error. Hope to have it fixed soon.

**Comment by smpallen99** [comment]
@nickarora Looks like a compile order issue. Not sure the fix yet, but workaround is to run `mix deps.compile` after you setup ex_admin in our config. There are some module attributes setup based on `Application.get_env :ex_admin, :module` which was not present when ex_admin was compiled.

@romul Do you want to take a look at a fix? Looks like this is the problem area: https://github.com/smpallen99/ex_admin/blob/master/lib/ex_admin/utils.ex#L8

**Comment by romul** [comment]
@smpallen99 Sure, I'll take a look tonight.

**Comment by romul** [comment]
@smpallen99 I think, it's fixed by https://github.com/romul/ex_admin/commit/9c53d74944629f2c54562f4a26a3b91ac983f549

**Comment by nickarora** [comment]
@romul In my post above, I note that config.exs includes the requisite addition -- yet I still experience this problem.  See the above for an excerpt from my config.exs

**Comment by nickarora** [comment]
@romul @smpallen9 I tested this again and fired the deps.get, deps.compile, and admin.install tasks only after all the configuration was completed, and didn't encounter the error.  It looks like it was a compile order issue -- thanks for the help and responsiveness!

**Comment by romul** [comment]
@nickarora Yeah, now you will get informative compile error in case of such the misconfiguration.
