### ISSUE TITLE
Changeset specification is ignored

### ISSUE THREAD

**Issue by holgerw** [smpallen99/ex_admin#221]
According to the documentation the **register_resource** block should support the specification of **custom changeset functions**, defined on the model, for the update and create action.

But this configuration seems to be ignored. Even specifying custom functions, ex_admin falls back to the default changeset function.

This feature was introduced by https://github.com/smpallen99/ex_admin/pull/36
As commented on the pull request the feature does not have a test associated.

**Comment by whitepaperclip** [comment]
+1

**Comment by RobinClowers** [comment]
Looks like this has been addressed and should be closed?

**Comment by whitepaperclip** [comment]
Agreed! @smpallen99 :)

(Might help if someone else had contributor status...)

**Comment by bsidoruk** [comment]
Is there any update on this?  I'm still seeing the issue.  I've had it work in the past but it has not worked for a while (I'm pulling from master).

**Comment by RobinClowers** [comment]
@bsidoruk It definitely was working, so it might be a regression if it's not working now.  Can you create a repro in a sample app?
